name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Debug DNS and Port
      #   run: |
      #     nslookup 54.79.117.167
      #     curl -v telnet://54.79.117.167:22

      - name: Deploy to EC2
        env:
          EC2_HOST: ubuntu@54.79.117.167
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_PROJECT_DIR: "/home/ubuntu/Portfolio/my-portfolio"
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_HOST << 'EOF'
            cd /home/ubuntu/Portfolio/my-portfolio

            # Ensure untracked changes are reset
            git reset --hard

            # Clean up old PM2 processes to prevent conflicts
            pm2 delete portfolio || true
            pm2 delete dashboard || true

            # Pull the latest changes
            git pull origin main

            # Install dependencies
            npm install

            # Build the Vite app
            npm run build || (echo "Retrying build..." && npm run build)

            # Start the Dashboard Service
            pm2 start "node src/server/server.js" --name "dashboard"
            pm2 save

            # Restart Nginx for the latest build
            sudo nginx -t && sudo systemctl restart nginx
          EOF
